{
    "openapi": "3.0.2",
    "info": {
        "title": "Marble-Race-API",
        "version": "1.0.0",
        "description": "### This is a Swagger UI for our Marble Race API  \n\n### Error handling\nErrors are presented using the HTTP status codes 400-599. The response include a more detailed explanation about the error in the body.\n\n```\n{\n  \"error\": \"Cleartext explanation of the error that occurred\"\n}\n```\n\n### Generic API errors\nThese error responses can be returned by any of the described endpoints.\n\n| HTTP status  |  Description |\n|---|---|\n| 400| Bad input parameters or invalid request. More information can be found in the response body.\n| 401| The consumer does not have access to the requested resource or the provided token is not valid.\n| 404| The requested resource can not be found or the user does not have access to the resource.\n| 5XX| A server error has occurred while processing the request."
    },
    "paths": {
    
        "/teams": {
            "get": {
                "tags": [
                    "teams"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "List of teams": {
                                        "value": [
                                            "Mellow Yellow",
                                            "Thunderbolts"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Returns a list of teams"
                    }
                },
                "operationId": "#184268094",
                "summary": "Get a list of teams",
                "description": "Returns a list of teams in API"
            },
            "post": {
                "requestBody": {
                    "description": "A new team to be created",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Teams"
                            },
                            "examples": {
                                "Muuda andmeid": {
                                    "value": {
                                        "teamName": "some text",
                                        "nrOfTeammates": 41,
                                        "teamLeader": "some text",
                                        "country": "some text"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "teams"
                ],
                "responses": {
                    "200": {
                        "description": "KÃµik korras"
                    },
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Teams"
                                },
                                "examples": {
                                    "Team data": {
                                        "value": {
                                            "id": 93,
                                            "teamName": "some text",
                                            "nrOfTeammates": 11,
                                            "teamLeader": "some text",
                                            "country": "some text"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Creates new entry with entered variables"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Missing parameters": {
                                        "value": {
                                            "error": "Parameters are missing"
                                        }
                                    },
                                    "NonUnique": {
                                        "value": {
                                            "error": "Data violates uniqueness rule"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "One or all params are missing"
                    }
                },
                "operationId": "#184268296",
                "summary": "Add teams",
                "description": "create new team, add variables"
            }
        },
        "/teams/{id}": {
            "get": {
                "tags": [
                    "teams"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Full details of a given team": {
                                        "value": [
                                            "Yellow Mellow",
                                            5,
                                            "Mellow",
                                            "Italy"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "returns full details"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "No examples were found": {
                                        "value": [
                                            "Team \\w+ was not found in team array"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Not found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Server error": {
                                        "value": [
                                            "L"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Suht pekkis"
                    }
                },
                "operationId": "#184268137",
                "summary": "get full details of team",
                "description": "returns details of given id"
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Teams"
                            },
                            "examples": {
                                "Edit this": {
                                    "value": {
                                        "teamName": "some text",
                                        "nrOfTeammates": 70,
                                        "teamLeader": "some text",
                                        "country": "some text"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "teams"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Teams"
                                },
                                "examples": {
                                    "Entry edited": {
                                        "value": [
                                            "Yellow Mellow",
                                            5,
                                            "Mellow",
                                            "Italy"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "guud"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Invalid data": {
                                        "value": {
                                            "error": "Invalid object data"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Invalid object data"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "id not found": {
                                        "value": {
                                            "error": "Id not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "not found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Server error": {
                                        "value": {
                                            "error": "Server error"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "server error"
                    }
                },
                "operationId": "#184438551",
                "summary": "update teams"
            },
            "delete": {
                "tags": [
                    "teams"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "schema": {
                            "type": "integer"
                        },
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Deleted"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "No permission": {
                                        "value": {
                                            "error": "No permission for this action"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "No permission"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "No pole": {
                                        "value": {
                                            "error": "Ei leidu"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Entry does not exist"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Server error": {
                                        "value": {
                                            "error": "pekki lÃ¤ks"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Server messed up"
                    }
                },
                "operationId": "#184268387",
                "summary": "Deletes team"
            },
            "parameters": [
                {
                    "name": "id",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        },
        "/competitions": {
            "get": {
                "tags": [
                    "competitions"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "List of Competitions": {
                                        "value": "[\n    \"VÃµistlus\"\n    \"MeistrivÃµistlus\"\n    ]"
                                    }
                                }
                            }
                        },
                        "description": "Returns a list of competitions"
                    }
                },
                "operationId": "#184267953",
                "summary": "Get a list of all competitions",
                "description": "Returns a list of all competitions in API"
            },
            "post": {
                "requestBody": {
                    "description": "A new competition to be created",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Competitions"
                            },
                            "examples": {
                                "Lisa andmed": {
                                    "value": {
                                        "competitionName": "some text",
                                        "date": "2018-01-17",
                                        "trackType": "some text",
                                        "numberOfTeams": 79,
                                        "registeredTeams": "some text",
                                        "location": "some text",
                                        "organizer": "some text"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "competitions"
                ],
                "responses": {
                    "200": {
                        "description": "KÃµik korras"
                    },
                    "201": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Competitions"
                                },
                                "examples": {
                                    "Example of entry": {
                                        "value": {
                                            "id": 74,
                                            "competitionName": "some text",
                                            "date": "2018-01-17",
                                            "trackType": "some text",
                                            "numberOfTeams": 62,
                                            "registeredTeams": "some text",
                                            "location": "some text",
                                            "organizer": "some text"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Creates new entry with entered variables"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Missing parameters": {
                                        "value": {
                                            "error": "Parameters are missing"
                                        }
                                    },
                                    "NonUnique": {
                                        "value": {
                                            "error": "Data violates uniqueness rule"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "One or all params are missing"
                    }
                },
                "operationId": "#184268298",
                "summary": "Add competitions and add info on lines for competitions",
                "description": "Create new competition, add variables\n"
            }
        },
        "/competitions/{id}": {
            "summary": "Get competition Details",
            "description": "Get all the details of a competition with the given id",
            "get": {
                "tags": [
                    "competitions"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "examples": {
                                    "Full details of a given competition": {
                                        "value": [
                                            "MeistrivÃµistlus",
                                            "20.04.2023",
                                            "Slaalom",
                                            5,
                                            "jama",
                                            "Tartu",
                                            "Bossworm"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Returns full details of a given id competition"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Competition /w+ was not found": {
                                        "value": {
                                            "error": "Competition \\w+ was not found in competition array"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Competition was not found in competitions array"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "No pekki": {
                                        "value": [
                                            "L"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Server error"
                    }
                },
                "operationId": "#184268001",
                "summary": "Get full details of a competition",
                "description": "Returns full details of a given id competition"
            },
            "put": {
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/Competitions"
                            },
                            "examples": {
                                "Edit this": {
                                    "value": {
                                        "competitionName": "some text",
                                        "date": "2018-01-17",
                                        "trackType": "some text",
                                        "numberOfTeams": 23,
                                        "registeredTeams": "some text",
                                        "location": "some text",
                                        "organizer": "some text"
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "tags": [
                    "competitions"
                ],
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Competitions"
                                },
                                "examples": {
                                    "Updated data": {
                                        "value": {
                                            "id": 77,
                                            "competitionName": "some text",
                                            "date": "2018-01-17",
                                            "trackType": "some text",
                                            "numberOfTeams": 39,
                                            "registeredTeams": "some text",
                                            "location": "some text",
                                            "organizer": "some text"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "All good"
                    },
                    "400": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Invalid data": {
                                        "value": {
                                            "error": "Invalid object data"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Invalid object data"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Id not found": {
                                        "value": {
                                            "error": "Id not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Not found"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Server error": {
                                        "value": {
                                            "error": "Server error"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Server fucke dup"
                    }
                },
                "operationId": "#184438658",
                "summary": "Update competitions"
            },
            "delete": {
                "tags": [
                    "competitions"
                ],
                "responses": {
                    "204": {
                        "description": "Deleted"
                    },
                    "403": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "No permission": {
                                        "value": {
                                            "error": "No permission for this action"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "No permission"
                    },
                    "404": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Not found": {
                                        "value": {
                                            "error": "Entry not found"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Entry does not exist"
                    },
                    "500": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/error"
                                },
                                "examples": {
                                    "Example": {
                                        "value": {
                                            "error": "Something went wrong on our side :/"
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Server messed up"
                    }
                },
                "operationId": "#184268390",
                "summary": "Delete competition"
            },
            "parameters": [
                {
                    "name": "id",
                    "schema": {
                        "type": "integer"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        },
        "/signUps": {
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "string"
                                },
                                "examples": {
                                    "List of signups": {
                                        "value": [
                                            "VÃµistlus",
                                            "Mellow Yellow"
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Returns a list of signups"
                    }
                },
                "summary": "Get a list of all Signups",
                "description": "Returns a list of all signups in API"
            }
        }
    },
    "components": {
        "schemas": {
            "error": {
                "title": "Root Type for error",
                "description": "",
                "type": "object",
                "properties": {
                    "error": {
                        "type": "string"
                    }
                },
                "example": {
                    "error": "Error message."
                }
            },
            "Teams": {
                "title": "Root Type for Teams",
                "description": "Team details",
                "required": [
                    "teamName",
                    "nrOfTeammates",
                    "country",
                    "teamLeader"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "",
                        "type": "integer",
                        "readOnly": true
                    },
                    "teamName": {
                        "description": "",
                        "type": "string"
                    },
                    "nrOfTeammates": {
                        "description": "",
                        "type": "integer"
                    },
                    "teamLeader": {
                        "description": "",
                        "type": "string"
                    },
                    "country": {
                        "description": "",
                        "type": "string"
                    }
                },
                "example": {
                    "id": 1,
                    "teamName": "some text",
                    "nrOfTeammates": 34,
                    "teamLeader": "some text",
                    "country": "some text"
                }
            },
            "Competitions": {
                "title": "Root Type for Competitions",
                "description": "Competition details",
                "required": [
                    "competitionName",
                    "date",
                    "trackType",
                    "numberOfTeams",
                    "registeredTeams",
                    "location",
                    "organizer"
                ],
                "type": "object",
                "properties": {
                    "id": {
                        "description": "",
                        "type": "integer",
                        "readOnly": true
                    },
                    "competitionName": {
                        "description": "",
                        "type": "string"
                    },
                    "date": {
                        "format": "date",
                        "description": "",
                        "type": "string"
                    },
                    "trackType": {
                        "description": "",
                        "type": "string"
                    },
                    "numberOfTeams": {
                        "description": "",
                        "type": "integer"
                    },
                    "registeredTeams": {
                        "description": "",
                        "type": "string"
                    },
                    "location": {
                        "description": "",
                        "type": "string"
                    },
                    "organizer": {
                        "description": "",
                        "type": "string"
                    }
                },
                "example": {
                    "id": 2,
                    "competitionName": "Eaaas",
                    "date": "2022-02-06",
                    "trackType": "Slaalom",
                    "numberOfTeams": 5,
                    "registeredTeams": "jama",
                    "location": "Tartu",
                    "organizer": "Bossworm"
                }
            }
        }
    }
}
